package main

import (
	"fmt"
	"log"
	"os"

	"github.com/izumin5210/dform/app/cmd"
	"github.com/izumin5210/dform/app/component"
	"github.com/izumin5210/dform/app/system"
)

var (
	// Name is application name
	Name string
	// Version is application version
	Version string
	// Revision describes current commit hash generated by `git describe --always`.
	Revision string
)

func main() {
	config := system.NewConfig(Name, Version, Revision)
	app := component.New(config)
	c := cmd.New(app)
	err := c.Execute()
	if err != nil {
		log.Fatalln(fmt.Errorf("failed to execute command: %v", err))
		os.Exit(-1)
	}
}
