#!/usr/bin/env bash

set -eu
set -o pipefail

NAME=the-dgraph
NETWORK=the_dgraph
IMAGE="dgraph/dgraph:master"
PORT_ZERO=9900
PORT_HTTP=9901
PORT_GRPC=9902
PORT_RATEL=9903


#  Commands
#-----------------------------------------------
_ping() {
  curl -LI localhost:$PORT_HTTP/health -o /dev/null -w '%{http_code}\n' -s | grep -q 200
}

server_start() {
  echo "==> Starting server"
  docker start $NAME 2>/dev/null || server_create

  echo "==> Starting Dgraph server"
  docker exec \
    -d \
    $NAME \
    dgraph server --bindall=true --memory_mb 2048 --zero localhost:5080

  echo "==> Starting Dgraph ratel"
  docker exec \
    -d \
    $NAME \
    dgraph-ratel -addr localhost:$PORT_HTTP

  echo "==> Waiting for ready"
  while true; do
    sleep 5
    if _ping; then
      echo
      echo "ready"
      break
    else
      printf '.'
    fi
  done

  echo "* ZERO:  $PORT_ZERO"
  echo "* HTTP:  $PORT_HTTP"
  echo "* gRPC:  $PORT_GRPC"
  echo "* Ratel: $PORT_RATEL"
}

server_create() {
  echo "==> Creating container and Dgraph zero"
  docker run \
    -p $PORT_ZERO:5080 \
    -p $PORT_HTTP:8080 \
    -p $PORT_GRPC:9080 \
    -p $PORT_RATEL:8081 \
    --name $NAME \
    --network $NETWORK \
    -v ~/docker/dgraph:/dgraph \
    -d \
    $IMAGE \
    dgraph zero --port_offset=-2000
}


server_stop() {
  echo "==> Stopping server"
  docker stop $NAME
}

server_destory() {
  echo "==> Destroying server"
  docker rm $NAME
}

exec_command() {
  docker exec -it $NAME "$@"
}

exec_logs() {
  docker logs -f $NAME
}

exec_status() {
  if docker ps | grep $NAME > /dev/null; then
    if _ping; then
      echo 'ready'
    else
      echo 'not ready'
    fi
  else
    echo 'not running'
  fi
}


#  Entrypoint
#-----------------------------------------------
COMMAND="${1:-}"
shift || true

case "$COMMAND" in
  start)    server_start ;;
  stop)     server_stop ;;
  destroy)  server_destory ;;
  exec)     exec_command "$@";;
  status)   exec_status ;;
  logs)     exec_logs ;;
esac
