version: '3'

services:
  app:
    build: .
    volumes:
      - ..:/app
      - vendor:/app/vendor
    networks:
      - the_dgraph
    command: tail -f /dev/null


volumes:
  vendor:

networks:
  the_dgraph:
    external: true
